name: My first WorkFlow
on: pull_request

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
         - name: Print message
           run: |
            echo "Hello, Github Action!"
                echo "Sehajpreet Singh"
                echo "pull request"
           
    say-name:
        runs-on: ubuntu-latest

        steps:
         - name: Print message
           run: echo "Sehajpreet Singh"


