# name: My first WorkFlow
# on: 
#     pull_request:
#     push:

# jobs:
#     say-hello:
#         runs-on: ubuntu-latest

#         steps:
#          - name: Print message
#            run: |
#             echo "Hello, Github Action!"
#                 echo "Sehajpreet Singh"
#                 echo "pull requesttry"
           
#     say-name:
#         needs: say-hello
#         runs-on: ubuntu-latest

#         steps:
#          - name: Print message
#            run: echo "Sehajpreet Singh"


# name: Uses action

# on: push

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: List files
#         run: ls -la

name: Uses action

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check Node version
        run: node -v

      - name: List files
        run: ls

      - name: download dependancy
        run: npm i
      
      - name: run test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy
        run: echo "deploye suyccess"
    
