name: My first WorkFlow
on: 
    pull_request:
    push:

jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
         - name: Print message
           run: |
            echo "Hello, Github Action!"
                echo "Sehajpreet Singh"
                echo "pull requesttry"
           
    say-name:
        needs: say-hello
        runs-on: ubuntu-latest

        steps:
         - name: Print message
           run: echo "Sehajpreet Singh"


